#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/Movie-Api
#    username: postgres
#    password: 8774
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Movie-Api
    username: root
    password: Rohan@498774
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
       # format_sql: true

project:
  poster: posters/

base:
  url: "http://localhost:8080"